spring.application.name=${APPLICATION_NAME}
spring.datasource.url=${DATA_SOURCE_URL}
spring.datasource.username=${DATA_SOURCE_USER_NAME}
spring.datasource.password=${DATA_SOURCE_USER_PASS}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
secom.validation.range.min=${SECOM_VALIDATION_RANGE.MIN}
secom.validation.range.max=${SECOM_VALIDATION_RANGE.MAX}
